import type { Game } from './types';

/** Games data — sourced from the existing ecosystem (ALT data model, MAIN content).
 *  Ranks, trophies and levels are real and kept exactly as they were recorded. */

export const games: Game[] = [
  {
    id: 'free-fire-max',
    name: 'Free Fire Max',
    image: './games/freefire.webp',
    nowPlaying: true,
    status: 'Main game · Rusher',
    badges: ['Grandmaster BR', 'Grandmaster CS', 'Rusher'],
    details: [
      'Highest rank: Grandmaster in both BR Ranked and CS Ranked.',
      'Role: Rusher — aggressive entry, first one in.',
      'Season-by-season ranks coming soon.',
    ],
    flex: 'Defeated many YouTubers in ranked matches.',
    verified: true,
    lastUpdated: '2026-09-07',
    hasProfile: true,
    profileRows: [
      { label: 'IGN', value: 'JustJayDev' },
      { label: 'Server', value: 'India' },
      { label: 'BR Rank', value: 'Grandmaster' },
      { label: 'CS Rank', value: 'Grandmaster' },
      { label: 'Role', value: 'Rusher' },
      { label: 'Device', value: 'realme 9 Pro 5G · 480 DPI' },
    ],
    accent: '#ff4d4d',
    category: 'main',
  },
  {
    id: 'fc-mobile',
    name: 'FC Mobile',
    image: './games/fcmobile.webp',
    nowPlaying: true,
    status: 'Main game · Football',
    badges: ['10★ Manager Mode', '5★ H2H', '7★ VSA', '126 OVR'],
    details: [
      'Division Rivals peaks: 10 Star Manager Mode · 5 Star H2H · 7 Star VSA.',
      'Best squad OVR: 126.',
      'Favourite card: TOTS Dembélé (Trickster) — best one.',
    ],
    verified: true,
    lastUpdated: '2026-09-07',
    hasProfile: true,
    profileRows: [
      { label: 'Manager Mode', value: '10★' },
      { label: 'H2H', value: '5★' },
      { label: 'VSA', value: '7★' },
      { label: 'Best OVR', value: '126' },
      { label: 'Fav Card', value: 'TOTS Dembélé' },
    ],
    accent: '#4de1ff',
    category: 'main',
  },
  {
    id: 'dragon-city',
    name: 'Dragon City',
    image: './games/dragoncity.webp',
    nowPlaying: true,
    status: 'Main game · Dragon collector',
    badges: ['Lv 55', '163/2217 Dragonbook', 'SHURA GOD', '161 Unique Dragons'],
    details: [
      'Level 55 — account linked, breeding and feeding daily.',
      'Dragonbook: 163 of 2217 dragons collected.',
      'Alliance: SHURA GOD — 19,217 total trophies · 2,009 master points.',
      'Top dragon: High Famine Dragon (Lv 45) — High Reborn, Terra Titan, Skullface, Pixel & High Zephyr all at Lv 40.',
      'Collection spans High-tier, Zodiac (Gemini · Virgo · Capricorn), Pure and event legendaries like Independence Day & Trick or Treat dragons.',
    ],
    flex: '161 unique dragons — including High-tier and Zodiac legendaries most players never hatch.',
    verified: true,
    lastUpdated: '2026-09-08',
    hasProfile: true,
    accent: '#ffd24d',
    category: 'main',
  },
  {
    id: 'roblox',
    name: 'Roblox',
    image: './games/roblox.webp',
    status: 'Grinder',
    badges: ['30M Bounty', 'V4 Max', 'Titanic Pets'],
    details: [
      'Pet Simulator 99: owned many Titanic and Huge pets (top-tier).',
      'Blox Fruits: ALL permanent fruits except mythical, Dark Blade unlocked, race V4 max, max level.',
      '30M bounty in BOTH Marines and Pirates.',
    ],
    verified: true,
    hasProfile: true,
    profileRows: [
      { label: 'Bounty', value: '30M (Marines + Pirates)' },
      { label: 'Race', value: 'V4 Max' },
      { label: 'Fruits', value: 'All permanent (excl. mythical)' },
      { label: 'Dark Blade', value: 'Unlocked' },
      { label: 'Pets', value: 'Titanic & Huge' },
    ],
    accent: '#9d4dff',
    category: 'main',
  },
  {
    id: 'minecraft',
    name: 'Minecraft',
    image: './games/minecraft.webp',
    status: 'Since 2019',
    badges: ['Ender Dragon ×4', 'Mods & Add-ons'],
    details: [
      'Completed the game (Ender Dragon) 4 times.',
      'Playing since 2019.',
      'Loves add-ons and mods — that’s why worlds get restarted instead of always finished.',
    ],
    verified: true,
    accent: '#4dff7d',
    category: 'main',
  },
  {
    id: 'mobile-legends',
    name: 'Mobile Legends',
    image: './games/mlbb.webp',
    status: 'Casual veteran',
    badges: ['Mythic tier'],
    details: [
      'Reached above Legendary — Mythic tier.',
      'Played casually; the game got boring after a while.',
    ],
    verified: true,
    accent: '#4d7dff',
    category: 'main',
  },
  {
    id: 'clash-royale',
    name: 'Clash Royale',
    image: './games/clashroyale.webp',
    status: 'Ladder grinder',
    badges: ['6,840 Trophies', 'Ultimate Champion', 'Fast Cycle'],
    details: [
      'Best rank: Ultimate Champion in Path of Legends.',
      'Peak trophies: 6,840 (Grand Champion arena range).',
      'Style: fast cycle decks — cheap wins, constant pressure.',
    ],
    verified: true,
    lastUpdated: '2026-09-18',
    accent: '#ff4dd2',
    category: 'main',
  },
  {
    id: 'brawl-stars',
    name: 'Brawl Stars',
    image: './games/brawlstars.webp',
    status: 'Casual ranked',
    badges: ['17,250 Trophies', 'Masters I', 'Edgar · Crow · Spike'],
    details: [
      'Total trophies: 17,250 across all brawlers.',
      'Ranked: Masters I in Ranked Mode.',
      'Mains: Edgar, Crow, Spike — all at high power levels.',
    ],
    verified: true,
    lastUpdated: '2026-09-18',
    accent: '#ffd24d',
    category: 'main',
  },
  {
    id: 'among-us',
    name: 'Among Us',
    image: './games/amongus.webp',
    status: 'For fun',
    badges: ['Certified Impostor'],
    details: [
      'Played for fun with friends.',
      'Certified Impostor.',
    ],
    verified: true,
    accent: '#ff4d4d',
    category: 'main',
  },
  {
    id: 'subway-surfers',
    name: 'Subway Surfers',
    status: 'Casual classic',
    badges: ['Endless runner'],
    details: ['One of the originals. Endless runs, no thinking required.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
  {
    id: 'temple-run',
    name: 'Temple Run',
    status: 'Casual classic',
    badges: ['Endless runner'],
    details: ['Classic endless runner with the cursed idol.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
  {
    id: 'hill-climb-racing',
    name: 'Hill Climb Racing',
    status: 'Casual classic',
    badges: ['Physics toy'],
    details: ['Physics-driven hill climbs. Good for passing time.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
  {
    id: 'candy-crush',
    name: 'Candy Crush',
    status: 'Casual classic',
    badges: ['Match-3'],
    details: ['The match-3 that started it all.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
  {
    id: '8-ball-pool',
    name: '8 Ball Pool',
    status: 'Casual classic',
    badges: ['Pool'],
    details: ['Flick the cue, sink the eight.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
  {
    id: 'ludo-king',
    name: 'Ludo King',
    status: 'Casual classic',
    badges: ['Board game'],
    details: ['Classic Ludo. Everyone has played it.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
  {
    id: 'chess',
    name: 'Chess',
    status: 'Casual classic',
    badges: ['Strategy'],
    details: ['Occasional casual games. Still counts.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
  {
    id: 'fruit-ninja',
    name: 'Fruit Ninja',
    status: 'Casual classic',
    badges: ['Swipe'],
    details: ['Swipe the fruit, dodge the bombs.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
  {
    id: 'angry-birds',
    name: 'Angry Birds',
    status: 'Casual classic',
    badges: ['Physics puzzle'],
    details: ['Pull back, let fly, knock things over.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
  {
    id: 'jetpack-joyride',
    name: 'Jetpack Joyride',
    status: 'Casual classic',
    badges: ['Endless runner'],
    details: ['Jetpack-fuel collecting endless run.'],
    accent: '#8fa3b0',
    category: 'casual',
  },
];

export const mainGames = games.filter((g) => g.category === 'main');
export const casualGames = games.filter((g) => g.category === 'casual');
export const nowPlaying = games.filter((g) => g.nowPlaying);

export const gameById = (id: string): Game | undefined =>
  games.find((g) => g.id === id);
