#!/usr/bin/env node
/* Generates the build-time static files that must stay in sync with the content
 * layer: feed.xml (from src/content/devlog.ts), sitemap.xml, and sw.js.
 *
 * The service-worker cache name is derived from the SHA-256 of the emitted
 * asset filenames, so it can never drift out of sync the way a hand-edited
 * version string did in the previous site.
 *
 * Run: node scripts/gen-static.mjs [--hash <string>]
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import * as esbuild from 'esbuild';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'dist');
const pub = path.join(root, 'public');
const SITE = 'https://justjaydev.github.io';

const esc = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(new RegExp('"', 'g'), '&#34;');

/* --- load the real content layer by transpiling it on the fly --- */
async function loadContent() {
  const tmp = path.join(root, 'node_modules', '.cache', 'content.mjs');
  await mkdir(path.dirname(tmp), { recursive: true });
  await esbuild.build({
    entryPoints: [path.join(root, 'src', 'content', 'index.ts')],
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    outfile: tmp,
    logLevel: 'silent',
  });
  return import(pathToFileURL(tmp).href + '?t=' + Date.now());
}

/* --- feed.xml --- */
function buildFeed(devlog, site) {
  const items = devlog
    .map((e) => {
      const link = `${SITE}/devlog#${e.slug}`;
      return `    <item>
      <title>${esc(e.title)}</title>
      <link>${link}</link>
      <guid isPermaLink="true">${link}</guid>
      <pubDate>${new Date(e.date + 'T09:00:00Z').toUTCString()}</pubDate>
      <description>${esc(e.excerpt)}</description>
    </item>`;
    })
    .join('\n');
  const newest = devlog[0].date;
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${esc(site.title)} — Devlog</title>
    <link>${SITE}/devlog</link>
    <atom:link href="${SITE}/feed.xml" rel="self" type="application/rss+xml"/>
    <description>Build notes for ${esc(site.title)}: the site, TitleForge, PixVault and the Developer Vault.</description>
    <language>en</language>
    <lastBuildDate>${new Date(newest + 'T09:00:00Z').toUTCString()}</lastBuildDate>
${items}
  </channel>
</rss>
`;
}

/* --- sitemap.xml --- */
function buildSitemap(paths) {
  const urls = paths
    .map((p) => {
      const loc = `${SITE}/${p.replace(/^\/+/, '')}`;
      const pri = p === '/' ? '1.0' : p === '/devlog' || p === '/games' ? '0.9' : '0.7';
      return `  <url>\n    <loc>${loc}</loc>\n    <changefreq>monthly</changefreq>\n    <priority>${pri}</priority>\n  </url>`;
    })
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

/* --- sw.js --- */
function buildSw(hash) {
  return `/* Generated by scripts/gen-static.mjs — do not edit by hand.
 * Cache version is derived from the build output hash. */
const CACHE = 'jjdev-v7-${hash}';
const SHELL = ['./', './index.html', './manifest.webmanifest'];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: network first so a fresh deploy is picked up immediately,
  // falling back to the cached shell when offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put('./index.html', copy));
          return res;
        })
        .catch(() => caches.match('./index.html')),
    );
    return;
  }

  // Hashed assets are immutable: cache first.
  if (/\\.[0-9a-z]{8,}\\.(js|css|woff2?|png|jpe?g|svg|webp|avif)$/i.test(url.pathname)) {
    event.respondWith(
      caches.match(req).then(
        (hit) =>
          hit ||
          fetch(req).then((res) => {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
            return res;
          }),
      ),
    );
  }
});
`;
}

const argv = process.argv.slice(2);
const hashArg = argv.includes('--hash') ? argv[argv.indexOf('--hash') + 1] : null;

let hash = hashArg;
if (!hash) {
  const assetsDir = path.join(out, 'assets');
  const names = existsSync(assetsDir)
    ? (await readdir(assetsDir)).sort()
    : (await readdir(pub)).sort();
  hash = createHash('sha256').update(names.join('|')).digest('hex').slice(0, 12);
}

await mkdir(out, { recursive: true });

// Static copies that live in public/ get written by Vite already; these three
// are generated so they can never disagree with the content layer.
const c = await loadContent();
await writeFile(path.join(out, 'feed.xml'), buildFeed(c.devlog, c.site));
// Derived from the content layer, not hand-listed, so a new game profile can
// never ship without being discoverable.
const sitemapPaths = [
  '/',
  '/games',
  '/projects',
  '/devlog',
  '/about',
  ...c.mainGames.filter((g) => g.hasProfile).map((g) => `/games/${g.id}`),
];
await writeFile(path.join(out, 'sitemap.xml'), buildSitemap(sitemapPaths));
await writeFile(path.join(out, 'sw.js'), buildSw(hash));

console.log(`gen-static: sw cache jjdev-v7-${hash}, feed=${c.devlog.length} entries`);
