/* Generated by scripts/gen-static.mjs — do not edit by hand.
 * Cache version is derived from the build output hash, so a new deploy always
 * lands in a new cache and the activate handler drops the old one.
 *
 * Registered from an ABSOLUTE '/sw.js' in src/main.tsx. A relative './sw.js'
 * resolved against the current document, so on a deep route it asked for
 * /games/dragon-city/sw.js, 404ed, and the visitor silently got no worker. */
const CACHE = 'jjdev-v8-d1857cbb0492';
const SHELL = ['/', '/index.html', '/manifest.webmanifest'];

/* One cache entry per real route, keyed by its own pathname. The previous
 * version wrote EVERY navigation into the single './index.html' slot, so the
 * most recently visited page replaced the shell for all of them: go offline
 * after visiting /devlog and /games/dragon-city served you the devlog HTML. */
const routeKey = (pathname) =>
  new URL(pathname.endsWith('/') ? pathname : pathname + '/', self.location.origin).pathname;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((c) => c.addAll(SHELL).catch(() => undefined))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: network first, so a fresh deploy is picked up on the next
  // visit. Cached per route, so an offline deep link still resolves to ITS OWN
  // page instead of whatever page was visited last. 404s are never cached --
  // caching one would pin a deleted page to a "live" response forever.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (res && res.status === 200) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(routeKey(url.pathname), copy));
          }
          return res;
        })
        .catch(() =>
          caches
            .match(routeKey(url.pathname))
            .then((hit) => hit || caches.match('/index.html')),
        ),
    );
    return;
  }

  // Hashed build output is immutable: cache first. Vite names these
  // <base>-<8 char hash>.ext, NOT a dot-suffixed hash, so the previous
  // pattern matched NONE of the 15 emitted assets and this arm was dead code.
  if (/-[A-Za-z0-9_-]{8}\.(js|css|woff2?|png|jpe?g|svg|webp|avif)$/i.test(url.pathname)) {
    event.respondWith(
      caches.match(req).then(
        (hit) =>
          hit ||
          fetch(req).then((res) => {
            if (res && res.status === 200) {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
            }
            return res;
          }),
      ),
    );
  }
});
